<div class="container-fluid text-center">
    <div class="row">
        <div class="text-left" id="contenido">

            <div class="container-fluid" id="form_ord">
                <h1>Ordenamiento de Credenciales (Periodo 2017B)</h1><br>
                <form name="ordenar-form" id="ordenar-form" action="<?= $this->url.'/sicred/ordenarcred'?>" method="post" class=" col-xs-4">
                    <div class="form-group">
                        <select id="plantel" name="plantel" class="form-control"  onchange="" required>
                            <option id="selection" value="">Seleccione un plantel</option>
                            <?php for ($i=1; $i<=20;$i++) {
                                if($band == 2){
                                    if ($i === (int)($data->plantel)) {?>
                                        <option id="<?= $i ?>" value="<?= $i ?>" selected> <?= $i ?> </option>
                                    <?php }else{ ?>
                                        <option id="<?= $i ?>" value="<?= $i ?>" > <?= $i ?> </option>
                                    <?php } ?>
                                <?php }else{ ?>
                                    <option id="<?= $i ?>" value="<?= $i ?>" > <?= $i ?> </option>
                                <?php } ?>
                            <?php }?>
                        </select>
                    </div>
                    <div class="form-group">
                        <input class="form-control input-sm" type="text" id="grupo" name="grupo" placeholder="Grupo">
                    </div>
                    <button class="btn btn-default" type="submit" id="serch-btn"> Generar listado </button>
                </form>
            </div>

            <?php if($band == 2){ ?>
                <div id="result">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <td>ID</td>
                            <td>MATRICULA</td>
                            <td>NOMBRE</td>
                            <td>GRUPO</td>
                            <td>FECHA DE IMPRESIÓN</td>
                            <td>FECHA DE VALIDACIÓN</td>
                            <td>ESTATUS</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $id= 1; ?>
                        <?php foreach ($lista as $alum){
                            if ($alum[6]==null || $alum[5]==null){?>
                                <tr>
                                    <td><?= $id ?></td>
                                    <td><?= $alum[0] ?></td>
                                    <td><?= $alum[1]." ".$alum[2]." ".$alum[3] ?></td>
                                    <td><?= $alum[4] ?></td>
                                    <td><?= $alum[5] ?></td>
                                    <td><?= $alum[6] ?></td>
                                    <td><p style="color:red">Impresión pendiente</p></td>
                                </tr>
                           <?php }elseif($alum[6]==3){ ?>
                                <tr>
                                    <td><?= $id ?></td>
                                    <td><?= $alum[0] ?></td>
                                    <td><?= $alum[1]." ".$alum[2]." ".$alum[3] ?></td>
                                    <td><?= $alum[4] ?></td>
                                    <td><?= $alum[5] ?></td>
                                    <td>Reimpresión pendiente</td>
                                </tr>
                           <?php }else{?>
                                <tr>
                                    <td><?= $id ?></td>
                                    <td><?= $alum[0] ?></td>
                                    <td><?= $alum[1]." ".$alum[2]." ".$alum[3] ?></td>
                                    <td><?= $alum[4] ?></td>
                                    <td><?= $alum[5] ?></td>
                                    <td><?= $alum[6] ?></td>
                                    <td>Impresa y validada</td>
                                </tr>
                            <?php }?>
                            <?php $id++;
                         }?>
                        </tbody>
                    </table>
                </div>
            <?php }?>
        </div>

    </div>
</div>
