<?php
    $title = 'Revisión de credenciales';
    $this->headTitle($title);
?>
<div class="text-center">
    <h1><?= $this->escapeHtml($title) ?></h1>
</div>

<div class="container-fluid text-left">
    <form name="serch-form" id="serch-form" action="<?= $this->url.'/sicred/serch'?>" method="post" class=" col-xs-4">
        <div class="form-group">
            <select id="plantel" name="plantel" class="form-control" required>
                <option id="selection" value="">Seleccione un plantel</option>
                <?php for ($i=1; $i<=25;$i++){ ?>
                    <option id="<?= $i ?>" value="<?= $i ?>"><?= $i ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="input-group">
            <input name="serch" id="serch" type="text" class="form-control" placeholder="Buscar matrícula..." minlength="9" maxlength="9" required onkeyup="javascript:this.value=this.value.toUpperCase();" value="" autocomplete="off">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit" id="serch-btn"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>
</div>

