<?php
$title = 'Revisión de credenciales';
$this->headTitle($title);
$size = count($resultSerch);
?>
<h3><?= $this->escapeHtml($title) ?></h3>
<div class="container">
    <form name="serch-form" id="serch-form" action="<?= $this->url.'/sicred/serch'?>" method="post" class=" col-xs-4">
        <div class="form-group">
            <select id="plantel" name="plantel" class="form-control" required>
                <option id="selection" value="">Seleccione un plantel</option>
                <?php for ($i=1; $i<=25;$i++) {
                    if ($i === (int)($resultSerch["plantel"])) {
                        ?>
                        <option id="<?= $i ?>" value="<?= $i ?>" selected><?= $i ?></option>
                    <?php } else { ?>
                        <option id="<?= $i ?>" value="<?= $i ?>"><?= $i ?></option>
                    <?php }
                }?>
            </select>
        </div>
        <div class="input-group">
            <input name="serch" id="serch" type="text" class="form-control" placeholder="Buscar matrícula..." minlength="9" maxlength="9" required onkeyup="javascript:this.value=this.value.toUpperCase();" value="" autocomplete="off">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit" id="serch-btn"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>
</div>
<br><br>
<div class="container">
    <?php if($size != 2){ ?>
        <h4><b><?= $resultSerch["matricula"] ?></b></h4>
        <table class="table table-hover">
            <tr>
                <td id="photo" rowspan="4"><center><img src="<?= $this->basePath('img/bachilleres.png') ?>"/></center></td>
                <td colspan="2"><?= $resultSerch["nombre"] ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $resultSerch["plantel"] ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $resultSerch["curp"] ?></td>
            </tr>
        </table>
   <?php }else{?>
        <h4>No se encontró la matrícula <b><?= $resultSerch["serch"]?></b></h4>
   <?php }?>


</div>
