<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Assistant" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Happy Monkey' rel='stylesheet'>
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <?= $this->headTitle('SiCred')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/bachilleres.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

        <script>
            $(document).ready(function () {
                $("#serch").on('keypress', function (tecla) {
                    if((tecla.charCode < 48 || tecla.charCode > 57) && (tecla.charCode < 97 || tecla.charCode >122) && (tecla.charCode < 65 || tecla.charCode > 90) && (tecla.charCode != 13)){
                        alert("Caracter no válido");
                        return false;
                    }
                });
            });
            $(document).ready(function () {
                $(".close").click(function () {
                    $("#alert").alert("close");
                })
            });
            $(document).ready(function () {
                $("#ok-btn").click(function () {
                    $.ajax({
                        type: "POST",
                        async: false,
                        cache: false,
                        url: "<?= $this->basePath('Prueba/agregarCredencial.php')?>",
                        data: "inp-matricula=" + document.getElementById("inp-matricula").value+
                        "&inp-nombre="+document.getElementById("inp-nombre").value+
                        "&inp-plantel="+document.getElementById("inp-plantel").value,
                        success: function (msg) {
                            document.getElementById('alert-info').style.display = 'block';
                        },
                        beforeSend: function (xhr) {
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                        }
                    });
                });
            });
        </script>

    </head>
    <body>
        <div id="header" class="jumbotron">
            <table>
                <tr>
                    <td>
                        <img src="<?= $this->basePath('img/logo_colegio_de_bachilleres.gif')?>" height="30%" width="30%" alt="Colegio de Bachilleres" class="img-responsive">
                    </td>
                    <td colspan="3">
                        <h1 id="sicred" class="text-center font-weight-bold" style="font-size: 28px">SiCred</h1><br>
                        <p id="sicred" class="text-center" style="font-size: 15px">Sistema de Credenciales</p>
                    </td>
                    <td style="text-align: left">
                        <?php $date = getdate();?>
                        <h5 class="text-left" style="text-align: left"><?= $date['mday']."/".$date['mon']."/".$date['year'] ?></h5>
                    </td>
                 </tr>
             </table>
        </div>
        <div id="contenido"class="container"">
            <?= $this->content ?>
        </div>
        <br><br>
        <footer class="container">
            <br><br>
            <p class="text-center font-weight-bold"><b>Prolongación Rancho Vista Hermosa No. 105 Col. Los Girasoles C.P. 04920 Coyoacán México D.F.</b></p>
        </footer>
        <?=$this->inlineScript() ?>
    </body>
</html>