<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Assistant" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <?= $this->headTitle('SiCred')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/bachilleres.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

    </head>
    <body>
        <?php
            $sesion = !empty($_SESSION);
        ?>
        <div class="container" id="header">
            <div class="jumbotron">
                <div id="div_titulo">
                    <h1 style="font-family: 'Lobster', cursive; position: absolute; top: 2%;">SiCred</h1>
                    <p style="top: 4%">Sistemas de Credenciales</p>

                </div>
                <div id="div_icon" class="img-responsive">
                    <img src="<?= $this->basePath('img/bachilleres.png')?>" class="img-responsive center-block">
                </div>
            </div>
            <nav id="navbar" class="navbar navbar-inverse">
                <div class="container-fluid">
                    <ul class="nav navbar-nav">
                        <li ><a href="<?= $this->basePath('sicred/index'); ?>">Home</a></li>
                        <?php if($sesion){ ?>
                            <li><a href="<?= $this->basePath('sicred/revisioncred'); ?>">Revisión de Credenciales</a></li>
                            <li><a href="<?= $this->basePath('sicred/ordenarcred'); ?>">Ordenamiento de Credenciales</a></li>
                        <?php }?>
                    </ul>
                    <?php if($sesion){ ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/sicred/logout"><span class="glyphicon glyphicon-log-out"></span> Salir </a></li>
                        </ul>
                    <?php } ?>
                </div>
            </nav>
        </div>
        <div id="contenido" class="container-fluid text-center">
            <?= $this->content ?>
            <hr>
            <!--footer id="footer" class="container-fluid text-center">
                <p class="text-center font-weight-bold"><b>Prolongación Rancho Vista Hermosa No. 105 Col. Los Girasoles C.P. 04920 Coyoacán México D.F.</b></p>
            </footer-->
        </div>

        <?=$this->inlineScript() ?>

        <script>
            $(document).ready(function () {
                $("#serch").on('keypress', function (tecla) {
                    if((tecla.charCode < 48 || tecla.charCode > 57) && (tecla.charCode < 97 || tecla.charCode >122) && (tecla.charCode < 65 || tecla.charCode > 90) && (tecla.charCode != 13)){
                        alert("Caracter no válido");
                        return false;
                    }
                });
            });
            $(document).ready(function () {
                $(".close").click(function () {
                    $("#alert").alert("close");
                })
            });
            $(document).ready(function () {
                $("#reporte").is(function () {
                    $("#radio").show();
                })
            });
            $(document).ready(function () {
                $("input[type=checkbox]").on('click', function(){
                    $("#msg_err").show();
                    $("#status").attr("value","2");
                })
            });
            $(document).ready(function () {
                $("#popup").click(function () {
                    $.ajax({
                        type: "POST",
                        async: false,
                        cache: false,
                        url: "<?= '/sicred/ordenarcred'?>",
                        data: "inp-matricula=" + document.getElementById("inp-matricula").value+
                        "&inp-nombre="+document.getElementById("inp-nombre").value+
                        "&inp-plantel="+document.getElementById("inp-plantel").value,
                        success: function (msg) {
                            document.getElementById('alert-info').style.display = 'block';
                        },
                        beforeSend: function (xhr) {
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                        }
                    });
                });
            });
        </script>
    </body>
</html>